'use client';

import Link from 'next/link';
import { ArrowRight, CalendarDays, Map, MapPin, Sparkles, TrainFront } from 'lucide-react';
import { MiniJourney, PageFrame, SectionHeading, StatPill } from '@/components/railyatra/railyatra-ui';

const PLANS = [
  { title: 'A slow weekend in Goa', route: 'Bilaspur → Madgaon', meta: '3 days · overnight', image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80' },
  { title: 'The royal triangle', route: 'Delhi → Jaipur → Udaipur', meta: '5 days · heritage', image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1000&q=80' },
  { title: 'Hills after the rain', route: 'Delhi → Kalka → Shimla', meta: '4 days · mountain', image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=80' },
];

export default function PlanPage() {
  return <PageFrame><main className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-12 lg:py-14"><SectionHeading eyebrow="Plan with intention" title="Make room for the journey." description="Start with a place, a weekend, or a feeling. RailYatra helps shape the route around you." /><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[28px] bg-[#0f2b43] p-7 text-white sm:p-10"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e7b75e] text-[#07111f]"><Sparkles className="h-5 w-5" /></span><span className="eyebrow text-[#f4d58d]">Yatri trip planner</span></div><h2 className="mt-8 max-w-xl font-serif text-4xl font-semibold leading-tight tracking-[-.04em]">“I have three days and want to feel somewhere different.”</h2><p className="mt-5 max-w-lg text-sm leading-7 text-white/65">Yatri can turn that into a route, a pace, and a shortlist of trains. You stay in control of every choice.</p><Link href="/chat" className="mt-8 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#e7b75e] px-5 text-sm font-semibold text-[#07111f]">Start with Yatri <ArrowRight className="h-4 w-4" /></Link></div><div className="rounded-[28px] border border-[#e2ddd3] bg-white p-7"><p className="eyebrow text-[#9a6b28]">Build a trip</p><h2 className="mt-3 font-serif text-3xl font-semibold">A simple starting point.</h2><div className="mt-6 space-y-3"><div className="flex items-center gap-3 rounded-2xl border border-[#e2ddd3] p-3"><MapPin className="h-4 w-4 text-[#9a6b28]" /><div><p className="text-xs text-[#8b95a2]">I want to go from</p><p className="text-sm font-semibold">Bilaspur</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-[#e2ddd3] p-3"><Map className="h-4 w-4 text-[#9a6b28]" /><div><p className="text-xs text-[#8b95a2]">I am curious about</p><p className="text-sm font-semibold">The western coast</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-[#e2ddd3] p-3"><CalendarDays className="h-4 w-4 text-[#9a6b28]" /><div><p className="text-xs text-[#8b95a2]">I have</p><p className="text-sm font-semibold">A long weekend</p></div></div></div><Link href="/search" className="mt-5 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#152338] text-sm font-semibold text-white">See train ideas <TrainFront className="h-4 w-4" /></Link></div></div><div className="mt-16"><SectionHeading eyebrow="Made for your pace" title="A few places to begin" action={<div className="flex flex-wrap gap-2"><StatPill icon={CalendarDays} label="Planning horizon" value="Flexible" /></div>} /><div className="grid gap-5 md:grid-cols-3">{PLANS.map((plan) => <MiniJourney key={plan.title} {...plan} />)}</div></div></main></PageFrame>;
}
