from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional


class AIResponse(BaseModel):
    """
    Structured response model returned by the Workflow layer to clients.
    Guarantees extensibility for future features.
    """

    response: str = Field(description="The final reply text generated by the agent.")
    agent: str = Field(
        description="The key/name of the specialist agent that processed the query."
    )
    intent: str = Field(description="The classified intent of the user message.")
    confidence: float = Field(
        default=1.0, description="The confidence score of the classification."
    )
    citations: List[str] = Field(
        default_factory=list,
        description="Source documents or policies cited by the agent.",
    )
    latency_ms: float = Field(
        default=0.0, description="Total execution time in milliseconds."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional contextual metadata (e.g. models, tokens).",
    )
    errors: List[str] = Field(
        default_factory=list,
        description="Any warnings, retries, or errors collected during execution.",
    )


class IntentCandidate(BaseModel):
    """
    Candidate intent classification output.
    """

    name: str = Field(description="The name of the intent candidate (e.g. plan_travel)")
    confidence: float = Field(
        default=1.0, description="Confidence score between 0.0 and 1.0"
    )
    reason: Optional[str] = Field(
        default=None, description="The reasoning behind the classification"
    )


class Slot(BaseModel):
    """
    An extracted slot value.
    """

    name: str = Field(description="Slot parameter name")
    value: Any = Field(description="Parsed slot value")
    type: str = Field(description="Slot parameter type validation label")
    confidence: float = Field(default=1.0, description="Extraction confidence score")


class IntentDescriptor(BaseModel):
    """
    Aggregate root representing the final validated semantic context.
    """

    intent: IntentCandidate = Field(description="Primary intent candidate")
    slots: Dict[str, Slot] = Field(
        default_factory=dict, description="Map of parsed slots"
    )
    context: Dict[str, Any] = Field(
        default_factory=dict, description="Trace context and PII flags"
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Operational timings and versions"
    )
    needs_clarification: bool = Field(default=False, description="Ambiguity flag")
