from pydantic import BaseModel, Field
from typing import Dict, Any, List


class AIResponse(BaseModel):
    """
    Structured response model returned by the Workflow layer to clients.
    Guarantees extensibility for future features.
    """

    response: str = Field(description="The final reply text generated by the agent.")
    agent: str = Field(
        description="The key/name of the specialist agent that processed the query."
    )
    intent: str = Field(description="The classified intent of the user message.")
    confidence: float = Field(
        default=1.0, description="The confidence score of the classification."
    )
    citations: List[str] = Field(
        default_factory=list,
        description="Source documents or policies cited by the agent.",
    )
    latency_ms: float = Field(
        default=0.0, description="Total execution time in milliseconds."
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional contextual metadata (e.g. models, tokens).",
    )
    errors: List[str] = Field(
        default_factory=list,
        description="Any warnings, retries, or errors collected during execution.",
    )
